#!/usr/bin/env bash

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"

sketchybar --bar position=bottom height=22 blur_radius=30 color=0x40000000


default=(
  padding_left=3
  padding_right=3
  icon.font="Hack Nerd Font:Bold:14.0"
  icon.padding_left=3
  icon.padding_right=0
  icon.color=0xffffffff
  label.font="Hack Nerd Font:Bold:14.0"
  label.padding_left=0
  label.padding_right=3
  label.color=0xffffffff
)
sketchybar --default "${default[@]}"


### CCWASHERE DISABLE Front App
#sketchybar --add item chevron left \
#           --set chevron icon= label.drawing=off \
#           --add item front_app left \
#           --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
#           --subscribe front_app front_app_switched
#

sketchybar \
   --add item clock right \
   --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
   \
   --add item battery right \
   --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
   --subscribe battery system_woke power_source_change \
   \
   --add item volume right \
   --set volume script="$PLUGIN_DIR/volume.sh" \
   --subscribe volume volume_change \


##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update

# rather than the typical listing below, instead we'd like 0 to be on the right
#aerospace list-workspaces --all
workspaces=$(\
    aerospace list-workspaces --all \
    | awk '{for(i=1;i<=NF;i++) if($i!=0) arr[++j]=$i} END {for(i=1;i<=j;i++) printf "%s ", arr[i]; print "0"}'\
)
sketchybar --add event aerospace_workspace_change
for sid in $workspaces; do
    sketchybar \
        --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid \
        label=${sid} \
        script="$CONFIG_DIR/plugins/aerospace.sh $sid" \
        click_script="aerospace workspace $sid" \
        background.color=0x44ffffff \
        background.corner_radius=5 \
        background.height=20 \
        background.drawing=off
done


